version: '3.7'

services:

    db:
        image: mysql
        container_name: db-app
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root

    front:
        build: './front'
        container_name: front-app
        volumes:
            - './front:/app'
            - '/app/node_modules'
        ports:
            - '8081:8080'

    back:
        build: './back'
        container_name: back-app
        ports:
            - "8080:80"
        volumes:
            - ./back:/var/www/html